[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  TERM = "xterm"
  NODE_VERSION = "18"
  
[[redirects]]
  from = "/quickmd"
  to = "https://ss-quick-md-editor.vercel.app"
  status = 301
